# Generated by Django 4.0.2 on 2022-04-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergeno', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Alergenos',
            },
        ),
    ]
