# Generated by Django 4.0.2 on 2022-04-12 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('elaboraciones', '0001_squashed_0003_alter_elaboracion_alergenos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('elaboracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elaboraciones.elaboracion')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('producto_elaboracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elaboracion_como_ingrediente', to='elaboraciones.elaboracion')),
            ],
            options={
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
