# Generated by Django 4.0.2 on 2022-05-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=75)),
                ('precio', models.FloatField(default=0)),
                ('iva', models.FloatField(default=10.0)),
                ('cantidad', models.FloatField(default=1)),
                ('unidad_medida', models.CharField(choices=[('g', 'gramos'), ('kg', 'kilogramos'), ('l', 'litros'), ('u', 'unidades')], default='u', max_length=10)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
