# Generated by Django 4.0.2 on 2022-04-20 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Elaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('tamano_racion', models.FloatField(default=1.0)),
                ('numero_raciones', models.FloatField(default=1.0)),
                ('tiempo_produccion', models.FloatField(default=0)),
                ('familia', models.CharField(blank=True, default='', max_length=25)),
                ('formato', models.CharField(blank=True, default='', max_length=25)),
                ('sabor', models.CharField(blank=True, default='', max_length=25)),
                ('producto_base', models.CharField(blank=True, default='', max_length=25)),
                ('preparacion', models.TextField()),
                ('link_foto', models.URLField(blank=True, default='')),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizado', models.DateTimeField(default=django.utils.timezone.now)),
                ('alergenos', models.ManyToManyField(blank=True, to='alergenos.Alergeno')),
            ],
            options={
                'verbose_name_plural': 'Elaboraciones',
            },
        ),
    ]
