# Generated by Django 4.0.2 on 2022-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboraciones', '0001_squashed_0003_alter_elaboracion_alergenos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaboracion',
            name='familia',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='elaboracion',
            name='formato',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='elaboracion',
            name='link_foto',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='elaboracion',
            name='producto_base',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='elaboracion',
            name='sabor',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
