# Generated by Django 4.0.2 on 2022-05-05 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefono debe introducirse en el formato: '+999999999'. Se aceptan hasta 15 dígitos.", regex='^$|^\\+?1?\\d{9,15}$')]),
        ),
    ]
